packages:
  - ./apps/*
  - ./packages/*

catalog:
  '@acdh-oeaw/eslint-config': ^2.0.10
  '@acdh-oeaw/eslint-config-next': ^4.0.3
  '@acdh-oeaw/eslint-config-node': ^2.0.10
  '@acdh-oeaw/eslint-config-playwright': ^2.0.12
  '@acdh-oeaw/eslint-config-react': ^3.0.2
  '@acdh-oeaw/eslint-config-storybook': ^4.0.0
  '@acdh-oeaw/eslint-config-tailwindcss': ^3.0.2
  '@acdh-oeaw/lib': ^0.3.5
  '@acdh-oeaw/prettier-config': ^2.0.1
  '@acdh-oeaw/style-variants': ^0.1.0
  '@acdh-oeaw/stylelint-config': ^2.3.2
  '@acdh-oeaw/tsconfig': ^1.5.1
  '@acdh-oeaw/validate-env': ^0.1.1
  '@fontsource-variable/fira-code': ^5.2.7
  '@fontsource-variable/inter': ^5.2.8
  '@heroicons/react': ^2.2.0
  '@next/eslint-plugin-next': ^16.0.1
  '@playwright/test': ^1.57.0
  '@react-aria/optimize-locales-plugin': ^1.1.5
  '@react-aria/utils': ^3.31.0
  '@sentry/nextjs': ^10.25.0
  '@storybook/addon-a11y': ^10.1.2
  '@storybook/addon-docs': ^10.1.2
  '@storybook/addon-themes': ^10.1.2
  '@storybook/addon-vitest': ^10.1.2
  '@storybook/react-vite': ^10.1.2
  '@tailwindcss/postcss': ^4.1.17
  '@tailwindcss/vite': ^4.1.17
  '@types/node': ^24.10.0
  '@types/pg': ^8.15.6
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@valibot/i18n': ^1.0.0
  '@vitejs/plugin-react': ^5.1.1
  '@vitest/browser-playwright': ^4.0.14
  '@vitest/coverage-v8': ^4.0.14
  axe-core: ^4.11.0
  axe-playwright: ^2.2.2
  babel-plugin-react-compiler: ^1.0.0
  client-only: ^0.0.1
  clsx: ^2.1.1
  concurrently: ^9.2.1
  dotenv: ^17.2.3
  dotenv-cli: ^11.0.0
  dotenv-expand: ^12.0.3
  drizzle-dbml-generator: ^0.10.0
  drizzle-kit: ^1.0.0-beta.1-7722e6a
  drizzle-orm: ^1.0.0-beta.1-7722e6a
  drizzle-valibot: ^0.4.2-7722e6a
  eslint: ^9.39.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-turbo: ^2.6.1
  eslint-plugin-check-file: ^3.3.1
  eslint-plugin-drizzle: ^0.2.3-7722e6a
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-unicorn: ^62.0.0
  globals: ^16.5.0
  is-in-ci: ^2.0.0
  is-network-error: ^1.3.0
  lint-staged: ^16.2.6
  lucide-react: 0.553.0
  motion: ^12.23.24
  next: ^16.0.1
  next-devtools-mcp: ^0.3.2
  next-intl: ^4.5.1
  npm-run-all2: ^8.0.4
  null-loader: ^4.0.1
  pg: ^8.16.3
  playwright: ^1.57.0
  prettier: ^3.6.2
  react: ^19.2.0
  react-aria: ^3.44.0
  react-aria-components: ^1.13.0
  react-dom: ^19.2.0
  react-schemaorg: ^2.0.0
  schema-dts: ^1.1.5
  server-nodejs-only: ^0.0.1
  server-only: ^0.0.1
  sharp: ^0.34.5
  simple-git-hooks: ^2.13.1
  storybook: ^10.1.2
  stylelint: ^16.25.0
  tailwind-merge: ^3.4.0
  tailwind-variants: ^3.1.1
  tailwindcss: ^4.1.17
  tailwindcss-react-aria-components: ^2.0.1
  tsdown: ^0.17.0-beta.4
  tsx: ^4.20.6
  turbo: ^2.6.1
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  valibot: ^1.1.0
  vite: ^7.2.6
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.14

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

patchedDependencies:
  next: patches/next.patch

shellEmulator: true

strictDepBuilds: true
