packages:
  - ./apps/*
  - ./lib/*
  - ./packages/*

catalog:
  '@acdh-oeaw/color-schemes': ^0.1.0
  '@acdh-oeaw/eslint-config': ^2.0.12
  '@acdh-oeaw/eslint-config-next': ^4.0.6
  '@acdh-oeaw/eslint-config-node': ^2.0.12
  '@acdh-oeaw/eslint-config-playwright': ^2.0.14
  '@acdh-oeaw/eslint-config-react': ^3.0.5
  '@acdh-oeaw/eslint-config-storybook': ^4.0.1
  '@acdh-oeaw/eslint-config-tailwindcss': ^4.1.3
  '@acdh-oeaw/lib': ^1.0.5
  '@acdh-oeaw/prettier-config': ^2.0.1
  '@acdh-oeaw/style-variants': ^0.1.0
  '@acdh-oeaw/stylelint-config': ^3.0.3
  '@acdh-oeaw/tsconfig': ^1.5.1
  '@acdh-oeaw/tsconfig-lib': ^1.3.0
  '@acdh-oeaw/validate-env': ^0.3.0
  '@chromatic-com/storybook': ^5.0.0
  '@dotenvx/dotenvx': ^1.52.0
  '@faker-js/faker': ^10.2.0
  '@fontsource-variable/fira-code': ^5.2.7
  '@fontsource-variable/inter': ^5.2.8
  '@heroicons/react': ^2.2.0
  '@hono/node-server': ^1.19.9
  '@hono/standard-validator': ^0.2.2
  '@hono/swagger-ui': ^0.5.3
  '@imgproxy/imgproxy-js-core': ^1.7.0
  '@imgproxy/imgproxy-node': ^1.1.0
  '@next/eslint-plugin-next': ^16.1.6
  '@playwright/test': ^1.58.0
  '@react-aria/optimize-locales-plugin': ^1.1.5
  '@react-aria/utils': ^3.31.0
  '@sentry/nextjs': ^10.36.0
  '@sentry/node': ^10.37.0
  '@sindresorhus/slugify': ^3.0.0
  '@storybook/addon-a11y': ^10.2.0
  '@storybook/addon-docs': ^10.2.0
  '@storybook/addon-themes': ^10.2.0
  '@storybook/addon-vitest': ^10.2.0
  '@storybook/react-vite': ^10.2.0
  '@tailwindcss/postcss': ^4.1.17
  '@tailwindcss/vite': ^4.1.17
  '@types/node': ^24.10.9
  '@types/nodemailer': ^7.0.5
  '@types/pg': ^8.16.0
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@valibot/i18n': ^1.0.0
  '@valibot/to-json-schema': ^1.5.0
  '@vitejs/plugin-react': ^5.1.1
  '@vitest/browser-playwright': ^4.0.14
  '@vitest/coverage-v8': ^4.0.14
  axe-core: ^4.11.1
  axe-playwright: ^2.2.2
  babel-plugin-react-compiler: ^1.0.0
  better-result: ^2.7.0
  client-only: ^0.0.1
  clsx: ^2.1.1
  concurrently: ^9.2.1
  drizzle-dbml-generator: ^0.10.0
  drizzle-kit: ^1.0.0-beta.12-a5629fb
  drizzle-orm: ^1.0.0-beta.12-a5629fb
  drizzle-seed: ^1.0.0-beta.12-a5629fb
  drizzle-valibot: ^1.0.0-beta.12-a5629fb
  eslint: ^9.39.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-turbo: ^2.8.0
  eslint-plugin-check-file: ^3.3.1
  eslint-plugin-drizzle: ^1.0.0-beta.12-a5629fb
  eslint-plugin-perfectionist: ^5.4.0
  eslint-plugin-unicorn: ^62.0.0
  globals: ^17.1.0
  hono: ^4.11.6
  hono-openapi: ^1.2.0
  hono-pino: ^0.10.3
  hono-rate-limiter: ^0.5.3
  is-in-ci: ^2.0.0
  is-network-error: ^1.3.0
  lint-staged: ^16.2.7
  lucide-react: ^0.563.0
  minio: ^8.0.6
  motion: ^12.29.2
  next: ^16.1.6
  next-devtools-mcp: ^0.3.10
  next-intl: ^4.8.0
  nodemailer: ^7.0.12
  npm-run-all2: ^8.0.4
  null-loader: ^4.0.1
  openapi-types: ^12.1.3
  pg: ^8.17.2
  pino: ^10.3.0
  pino-pretty: ^13.1.3
  playwright: ^1.58.0
  prettier: ^3.8.1
  prettier-plugin-embed: ^0.5.1
  prettier-plugin-sql: ^0.19.2
  react: ^19.2.1
  react-aria: ^3.44.0
  react-aria-components: ^1.13.0
  react-dom: ^19.2.1
  react-schemaorg: ^2.0.0
  schema-dts: ^1.1.5
  server-nodejs-only: ^0.0.1
  server-only: ^0.0.1
  sharp: ^0.34.5
  simple-git-hooks: ^2.13.1
  storybook: ^10.2.0
  storybook-next-intl: ^10.0.1
  stylelint: ^17.0.0
  stylelint-config-standard: ^40.0.0
  tailwind-merge: ^3.4.0
  tailwind-variants: ^3.2.2
  tailwindcss: ^4.1.17
  tailwindcss-react-aria-components: ^2.0.1
  tsdown: ^0.20.1
  tsx: ^4.21.0
  turbo: ^2.8.1
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typesense: ^2.1.0
  uuid: ^13.0.0
  valibot: ^1.2.0
  vite: ^7.2.6
  vite-tsconfig-paths: ^6.0.5
  vitest: ^4.0.18
  wp-types: ^4.69.0
  xast-util-feed: ^2.0.0
  xast-util-to-xml: ^4.0.0

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

patchedDependencies:
  next: patches/next.patch

shellEmulator: true

strictDepBuilds: true
