packages:
  - ./apps/*
  - ./packages/*

catalog:
  '@acdh-oeaw/prettier-config': ^2.0.1
  '@playwright/test': ^1.56.1
  is-in-ci: ^2.0.0
  lint-staged: ^16.2.6
  npm-run-all2: ^8.0.4
  prettier: ^3.6.2
  simple-git-hooks: ^2.13.1
  turbo: ^2.6.1
  typescript: ^5.9.3

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - simple-git-hooks

shellEmulator: true

strictDepBuilds: true
