packages:
  - ./apps/*
  - ./packages/*

catalog:
  '@acdh-oeaw/eslint-config': ^2.0.11
  '@acdh-oeaw/eslint-config-next': ^4.0.4
  '@acdh-oeaw/eslint-config-node': ^2.0.11
  '@acdh-oeaw/eslint-config-playwright': ^2.0.13
  '@acdh-oeaw/eslint-config-react': ^3.0.3
  '@acdh-oeaw/eslint-config-tailwindcss': ^4.0.2
  '@acdh-oeaw/lib': ^0.3.7
  '@acdh-oeaw/prettier-config': ^2.0.1
  '@acdh-oeaw/style-variants': ^0.1.0
  '@acdh-oeaw/stylelint-config': ^2.3.2
  '@acdh-oeaw/tsconfig': ^1.5.1
  '@acdh-oeaw/validate-env': ^0.2.1
  '@faker-js/faker': ^10.1.0
  '@heroicons/react': ^2.2.0
  '@next/eslint-plugin-next': ^16.0.8
  '@playwright/test': ^1.57.0
  '@react-aria/optimize-locales-plugin': ^1.1.5
  '@react-aria/utils': ^3.31.0
  '@sentry/nextjs': ^10.30.0
  '@tailwindcss/postcss': ^4.1.17
  '@types/node': ^24.10.3
  '@types/pg': ^8.16.0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@valibot/i18n': ^1.0.0
  axe-core: ^4.11.0
  axe-playwright: ^2.2.2
  babel-plugin-react-compiler: ^1.0.0
  client-only: ^0.0.1
  clsx: ^2.1.1
  concurrently: ^9.2.1
  dotenv: ^17.2.3
  dotenv-cli: ^11.0.0
  dotenv-expand: ^12.0.3
  drizzle-dbml-generator: ^0.10.0
  drizzle-kit: ^1.0.0-beta.2-ec83fa8
  drizzle-orm: ^1.0.0-beta.2-ec83fa8
  drizzle-valibot: ^0.4.2
  eslint: ^9.39.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-plugin-check-file: ^3.3.1
  eslint-plugin-drizzle: ^1.0.0-beta.2-58a4521
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-unicorn: ^62.0.0
  globals: ^16.5.0
  is-in-ci: ^2.0.0
  is-network-error: ^1.3.0
  lint-staged: ^16.2.7
  lucide-react: ^0.560.0
  motion: ^12.23.26
  next: ^16.0.8
  next-devtools-mcp: ^0.3.6
  next-intl: ^4.5.8
  npm-run-all2: ^8.0.4
  null-loader: ^4.0.1
  pg: ^8.16.3
  prettier: ^3.7.4
  react: ^19.2.1
  react-aria: ^3.44.0
  react-aria-components: ^1.13.0
  react-dom: ^19.2.1
  react-schemaorg: ^2.0.0
  schema-dts: ^1.1.5
  server-nodejs-only: ^0.0.1
  server-only: ^0.0.1
  sharp: ^0.34.5
  simple-git-hooks: ^2.13.1
  stylelint: ^16.26.1
  tailwind-merge: ^3.4.0
  tailwind-variants: ^3.2.2
  tailwindcss: ^4.1.17
  tailwindcss-react-aria-components: ^2.0.1
  tsx: ^4.21.0
  turbo: ^2.6.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typesense: ^2.1.0
  valibot: ^1.2.0
  xast-util-feed: ^2.0.0
  xast-util-to-xml: ^4.0.0

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

patchedDependencies:
  next: patches/next.patch

shellEmulator: true

strictDepBuilds: true
