#!/bin/sh

set -eu

API_ACCESS_TOKEN=$(openssl rand --hex 32)
AUTH_ENCRYPTION_KEY=$(openssl rand --hex 16)
AUTH_SIGN_UP="enabled"
DATABASE_PASSWORD=$(openssl rand --hex 32)
IMGPROXY_KEY=$(openssl rand --hex 32)
IMGPROXY_SALT=$(openssl rand --hex 16)
REVALIDATION_WEBHOOK_SECRET=$(openssl rand --hex 32)
SEARCH_SYNC_API_SECRET=$(openssl rand --hex 32)
S3_ACCESS_KEY=$(openssl rand --hex 16)
S3_SECRET_KEY=$(openssl rand --hex 32)
TYPESENSE_ADMIN_API_KEY=$(openssl rand --hex 32)

ENV_FILE=./.devcontainer/.env

if [ ! -f "$ENV_FILE" ]; then
	cp $ENV_FILE.example $ENV_FILE

	sed -i "s/AUTH_ENCRYPTION_KEY=.*/AUTH_ENCRYPTION_KEY=\"$AUTH_ENCRYPTION_KEY\"/" $ENV_FILE
	sed -i "s/DATABASE_PASSWORD=.*/DATABASE_PASSWORD=\"$DATABASE_PASSWORD\"/" $ENV_FILE
	sed -i "s/IMGPROXY_KEY=.*/IMGPROXY_KEY=\"$IMGPROXY_KEY\"/" $ENV_FILE
	sed -i "s/IMGPROXY_SALT=.*/IMGPROXY_SALT=\"$IMGPROXY_SALT\"/" $ENV_FILE
	sed -i "s/S3_ACCESS_KEY=.*/S3_ACCESS_KEY=\"$S3_ACCESS_KEY\"/" $ENV_FILE
	sed -i "s/S3_SECRET_KEY=.*/S3_SECRET_KEY=\"$S3_SECRET_KEY\"/" $ENV_FILE
	sed -i "s/TYPESENSE_ADMIN_API_KEY=.*/TYPESENSE_ADMIN_API_KEY=\"$TYPESENSE_ADMIN_API_KEY\"/" $ENV_FILE
fi

ENV_FILE=./apps/knowledge-base/.env.local

if [ ! -f "$ENV_FILE" ]; then
	cp $ENV_FILE.example $ENV_FILE

	sed -i "s/AUTH_ENCRYPTION_KEY=.*/AUTH_ENCRYPTION_KEY=\"$AUTH_ENCRYPTION_KEY\"/" $ENV_FILE
	sed -i "s/AUTH_SIGN_UP=.*/AUTH_SIGN_UP=\"$AUTH_SIGN_UP\"/" $ENV_FILE
	sed -i "s/DATABASE_PASSWORD=.*/DATABASE_PASSWORD=\"$DATABASE_PASSWORD\"/" $ENV_FILE
	sed -i "s/IMGPROXY_KEY=.*/IMGPROXY_KEY=\"$IMGPROXY_KEY\"/" $ENV_FILE
	sed -i "s/IMGPROXY_SALT=.*/IMGPROXY_SALT=\"$IMGPROXY_SALT\"/" $ENV_FILE
	sed -i "s/REVALIDATION_WEBHOOK_SECRET=.*/REVALIDATION_WEBHOOK_SECRET=\"$REVALIDATION_WEBHOOK_SECRET\"/" $ENV_FILE
	sed -i "s/SEARCH_SYNC_API_SECRET=.*/SEARCH_SYNC_API_SECRET=\"$SEARCH_SYNC_API_SECRET\"/" $ENV_FILE
	sed -i "s/S3_ACCESS_KEY=.*/S3_ACCESS_KEY=\"$S3_ACCESS_KEY\"/" $ENV_FILE
	sed -i "s/S3_SECRET_KEY=.*/S3_SECRET_KEY=\"$S3_SECRET_KEY\"/" $ENV_FILE
	sed -i "s/TYPESENSE_ADMIN_API_KEY=.*/TYPESENSE_ADMIN_API_KEY=\"$TYPESENSE_ADMIN_API_KEY\"/" $ENV_FILE
fi

ENV_FILE=./apps/website/.env.local

if [ ! -f "$ENV_FILE" ]; then
	cp $ENV_FILE.example $ENV_FILE

	sed -i "s/DATABASE_PASSWORD=.*/DATABASE_PASSWORD=\"$DATABASE_PASSWORD\"/" $ENV_FILE
	sed -i "s/IMGPROXY_KEY=.*/IMGPROXY_KEY=\"$IMGPROXY_KEY\"/" $ENV_FILE
	sed -i "s/IMGPROXY_SALT=.*/IMGPROXY_SALT=\"$IMGPROXY_SALT\"/" $ENV_FILE
	sed -i "s/REVALIDATION_WEBHOOK_SECRET=.*/REVALIDATION_WEBHOOK_SECRET=\"$REVALIDATION_WEBHOOK_SECRET\"/" $ENV_FILE
	sed -i "s/S3_ACCESS_KEY=.*/S3_ACCESS_KEY=\"$S3_ACCESS_KEY\"/" $ENV_FILE
	sed -i "s/S3_SECRET_KEY=.*/S3_SECRET_KEY=\"$S3_SECRET_KEY\"/" $ENV_FILE
	sed -i "s/TYPESENSE_ADMIN_API_KEY=.*/TYPESENSE_ADMIN_API_KEY=\"$TYPESENSE_ADMIN_API_KEY\"/" $ENV_FILE
fi

ENV_FILE=./apps/api/.env.local

if [ ! -f "$ENV_FILE" ]; then
	cp $ENV_FILE.example $ENV_FILE

	sed -i "s/API_ACCESS_TOKEN=.*/API_ACCESS_TOKEN=\"$API_ACCESS_TOKEN\"/" $ENV_FILE
	sed -i "s/DATABASE_PASSWORD=.*/DATABASE_PASSWORD=\"$DATABASE_PASSWORD\"/" $ENV_FILE
	sed -i "s/IMGPROXY_KEY=.*/IMGPROXY_KEY=\"$IMGPROXY_KEY\"/" $ENV_FILE
	sed -i "s/IMGPROXY_SALT=.*/IMGPROXY_SALT=\"$IMGPROXY_SALT\"/" $ENV_FILE
	sed -i "s/S3_ACCESS_KEY=.*/S3_ACCESS_KEY=\"$S3_ACCESS_KEY\"/" $ENV_FILE
	sed -i "s/S3_SECRET_KEY=.*/S3_SECRET_KEY=\"$S3_SECRET_KEY\"/" $ENV_FILE
fi

echo "✓ Environment variables initialized."
